# -*- coding: utf-8 -*-
"""Task_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EEZVvnFsQ5dvy9aPEVSUrqi0d9YaLJy7

**PRODIGY INFOTECH INTERNSHIP**

**TASK 2**:Perform data cleaning and exploratory data analysis (EDA) on a dataset of your choice, such as the Titanic dataset from Kaggle. Explore the relationships between variables and identify patterns and trends in the data.

**DONE BY**: SUSMITA JEVOOR
**Email**:smita.jevoor@gmail.com
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('train.csv')
df.head()

df.info()

df.isna().sum()

df.dropna(inplace=True)
df_1=df.drop_duplicates()
df_1.info

pclass_names={
    1:'First Class',
    2:'Second Class',
    3:'Third Class'
}
df['Pclass name']=df['Pclass'].map(pclass_names)
df.head()

df['Family']=df["SibSp"]+df["Parch"]
df.head()

df.describe().T

cont_val=df[['PassengerId','Survived','Pclass','Age','SibSp','Parch','Fare','Embarked','Family']]
sns.set_style('darkgrid')
sns.set_palette('pastel')
sns.heatmap(cont_val.corr(),cmap='viridis',annot=True)

sns.countplot(data=df,x="Pclass name",hue='Sex',color='salmon')
plt.title("Distribution of passenger's classes")

sns.set_style('white')
sns.displot(data=df,x="Age",bins=15,hue='Survived',palette='muted',hue_order=[1,0])
plt.title("Distribution by age")

sns.displot(data=df,x='Family',bins=10)
plt.title("Distribution of passenger's family members")

